# Generated by Django 4.2.13 on 2024-06-05 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecapp", "0002_remove_itemmodel_comment_delete_comment"),
    ]

    operations = [
        migrations.RemoveField(model_name="itemmodel", name="genre",),
        migrations.AddField(
            model_name="itemmodel",
            name="genre",
            field=models.ForeignKey(
                default=4, on_delete=django.db.models.deletion.CASCADE, to="ecapp.genre"
            ),
        ),
    ]
