# Generated by Django 4.2.13 on 2024-06-05 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecapp", "0003_remove_itemmodel_genre_itemmodel_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmodel",
            name="genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ecapp.genre"
            ),
        ),
    ]
