# Generated by Django 4.2.13 on 2024-06-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecapp", "0005_remove_itemmodel_good_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemmodel",
            name="aold",
            field=models.BooleanField(default=False),
        ),
    ]
