# Generated by Django 4.2.13 on 2024-06-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecapp", "0007_rename_aold_itemmodel_sold"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemmodel",
            name="price_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
